import type { Article, Transfer, Match, Player, Club, Source } from '@/types';

export const SOURCES: Source[] = [
  { id: 's1', name: 'L\'Équipe', logo: '/logos/lequipe.svg', url: 'https://www.lequipe.fr', trusted: true, country: 'France' },
  { id: 's2', name: 'RMC Sport', logo: '/logos/rmc.svg', url: 'https://rmcsport.bfmtv.com', trusted: true, country: 'France' },
  { id: 's3', name: 'FootMercato', logo: '/logos/footmercato.svg', url: 'https://www.footmercato.net', trusted: true, country: 'France' },
  { id: 's4', name: 'Sky Sports', logo: '/logos/skysports.svg', url: 'https://www.skysports.com', trusted: true, country: 'Angleterre' },
  { id: 's5', name: 'BBC Sport', logo: '/logos/bbc.svg', url: 'https://www.bbc.com/sport/football', trusted: true, country: 'Angleterre' },
  { id: 's6', name: 'ESPN', logo: '/logos/espn.svg', url: 'https://www.espn.com', trusted: true, country: 'USA' },
  { id: 's7', name: 'Fanatik DZ', logo: '/logos/fanatidk.svg', url: 'https://www.fanatiquez.dz', trusted: true, country: 'Algérie' },
  { id: 's8', name: 'Le Buteur', logo: '/logos/lebuteur.svg', url: 'https://www.lebuteur.com', trusted: true, country: 'Algérie' },
];

export const CLUBS: Club[] = [
  { id: 'c1', name: 'Paris Saint-Germain', logo: '🔵', league: 'Ligue 1', country: 'France', color: '#001F5B' },
  { id: 'c2', name: 'Real Madrid', logo: '⚪', league: 'La Liga', country: 'Espagne', color: '#FEBE10' },
  { id: 'c3', name: 'Manchester City', logo: '🔵', league: 'Premier League', country: 'Angleterre', color: '#6CABDD' },
  { id: 'c4', name: 'Bayern Munich', logo: '🔴', league: 'Bundesliga', country: 'Allemagne', color: '#DC052D' },
  { id: 'c5', name: 'Inter Milan', logo: '⚫', league: 'Serie A', country: 'Italie', color: '#003DA5' },
  { id: 'c6', name: 'Arsenal', logo: '🔴', league: 'Premier League', country: 'Angleterre', color: '#EF0107' },
  { id: 'c7', name: 'Atletico Madrid', logo: '🔴', league: 'La Liga', country: 'Espagne', color: '#CE3524' },
  { id: 'c8', name: 'Équipe Nationale Algérie', logo: '🇩🇿', league: 'CAN', country: 'Algérie', color: '#006633' },
  { id: 'c9', name: 'Bayer Leverkusen', logo: '🔴', league: 'Bundesliga', country: 'Allemagne', color: '#E32221' },
  { id: 'c10', name: 'Liverpool', logo: '🔴', league: 'Premier League', country: 'Angleterre', color: '#C8102E' },
];

export const PLAYERS: Player[] = [
  {
    id: 'p1', name: 'Riyad Mahrez', position: 'Ailier droit', nationality: 'Algérie',
    age: 33, currentClub: CLUBS[0], imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=300&h=300&fit=crop',
    isAlgerian: true, jerseyNumber: 26, marketValue: '15M€',
  },
  {
    id: 'p2', name: 'Islam Slimani', position: 'Attaquant', nationality: 'Algérie',
    age: 35, currentClub: CLUBS[0], imageUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=300&h=300&fit=crop',
    isAlgerian: true, jerseyNumber: 9, marketValue: '3M€',
  },
  {
    id: 'p3', name: 'Youcef Atal', position: 'Latéral droit', nationality: 'Algérie',
    age: 28, currentClub: CLUBS[0], imageUrl: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=300&h=300&fit=crop',
    isAlgerian: true, jerseyNumber: 22, marketValue: '18M€',
  },
  {
    id: 'p4', name: 'Kylian Mbappé', position: 'Attaquant', nationality: 'France',
    age: 26, currentClub: CLUBS[1], imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c643e7f0b?w=300&h=300&fit=crop',
    isAlgerian: false, jerseyNumber: 9, marketValue: '180M€',
  },
  {
    id: 'p5', name: 'Andy Delort', position: 'Attaquant', nationality: 'Algérie',
    age: 32, currentClub: CLUBS[0], imageUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=300&h=300&fit=crop',
    isAlgerian: true, jerseyNumber: 11, marketValue: '5M€',
  },
];

export const ARTICLES: Article[] = [
  {
    id: 'a1',
    title: 'Mahrez dévoile ses ambitions pour la CAN 2025 avec l\'Algérie',
    summary: 'Le capitaine des Fennecs, Riyad Mahrez, a accordé une interview exclusive où il exprime sa détermination à remporter la Coupe d\'Afrique des Nations avec l\'équipe nationale algérienne.',
    imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=450&fit=crop',
    source: SOURCES[0],
    originalUrl: 'https://www.lequipe.fr',
    category: 'algerie',
    tags: ['Mahrez', 'Algérie', 'CAN 2025'],
    publishedAt: '2026-03-10T08:30:00Z',
    viewCount: 24500,
    isBreaking: false,
    isTrending: true,
    isPopular: true,
    league: 'CAN',
  },
  {
    id: 'a2',
    title: 'OFFICIEL : Mbappé prolonge au Real Madrid jusqu\'en 2029',
    summary: 'Le Real Madrid et Kylian Mbappé ont officialisé la prolongation de contrat de l\'attaquant français jusqu\'en 2029. Le joueur de 26 ans reste ainsi la star indétrônable du club madrilène.',
    imageUrl: 'https://images.unsplash.com/photo-1556056504-5c7696c4c328?w=800&h=450&fit=crop',
    source: SOURCES[3],
    originalUrl: 'https://www.skysports.com',
    category: 'transferts',
    tags: ['Mbappé', 'Real Madrid', 'Prolongation'],
    publishedAt: '2026-03-10T07:15:00Z',
    viewCount: 89200,
    isBreaking: true,
    isTrending: true,
    isPopular: true,
    league: 'La Liga',
  },
  {
    id: 'a3',
    title: 'Champions League : le PSG élimine le Bayern Munich en quarts de finale',
    summary: 'Dans un match épique au Parc des Princes, le Paris Saint-Germain a éliminé le Bayern Munich 3-2 sur l\'ensemble des deux matchs, se qualifiant ainsi pour les demi-finales de la Ligue des Champions.',
    imageUrl: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=800&h=450&fit=crop',
    source: SOURCES[1],
    originalUrl: 'https://rmcsport.bfmtv.com',
    category: 'matchs',
    tags: ['PSG', 'Bayern', 'Champions League'],
    publishedAt: '2026-03-09T23:00:00Z',
    viewCount: 112000,
    isBreaking: false,
    isTrending: true,
    isPopular: true,
    league: 'Champions League',
  },
  {
    id: 'a4',
    title: 'Atal reprend l\'entraînement collectif avant le match contre le Cameroun',
    summary: 'Bonne nouvelle pour les supporters des Fennecs ! Youcef Atal a repris l\'entraînement collectif avec le groupe et devrait être disponible pour le match qualificatif contre le Cameroun.',
    imageUrl: 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?w=800&h=450&fit=crop',
    source: SOURCES[7],
    originalUrl: 'https://www.lebuteur.com',
    category: 'algerie',
    tags: ['Atal', 'Algérie', 'Blessure', 'Cameroun'],
    publishedAt: '2026-03-10T06:45:00Z',
    viewCount: 31000,
    isBreaking: false,
    isTrending: false,
    isPopular: true,
    league: 'CAN',
  },
  {
    id: 'a5',
    title: 'Lamine Yamal : "Arsenal et City m\'ont approché cet hiver"',
    summary: 'La révélation espagnole Lamine Yamal a confirmé dans une interview que plusieurs grands clubs européens l\'avaient contacté lors du dernier mercato hivernal, mais qu\'il reste focalisé sur le Barça.',
    imageUrl: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&h=450&fit=crop',
    source: SOURCES[2],
    originalUrl: 'https://www.footmercato.net',
    category: 'transferts',
    tags: ['Yamal', 'Barcelone', 'Arsenal', 'Manchester City'],
    publishedAt: '2026-03-10T05:30:00Z',
    viewCount: 67800,
    isBreaking: false,
    isTrending: true,
    isPopular: false,
    league: 'La Liga',
  },
  {
    id: 'a6',
    title: 'Premier League : Arsenal en tête après la défaite de City',
    summary: 'Après la défaite surprise de Manchester City face à Newcastle (1-2), Arsenal revient en tête du classement de Premier League avec 2 points d\'avance sur les Citizens.',
    imageUrl: 'https://images.unsplash.com/photo-1540747913346-19212a4f9569?w=800&h=450&fit=crop',
    source: SOURCES[4],
    originalUrl: 'https://www.bbc.com/sport/football',
    category: 'matchs',
    tags: ['Arsenal', 'Manchester City', 'Premier League'],
    publishedAt: '2026-03-09T21:45:00Z',
    viewCount: 45300,
    isBreaking: false,
    isTrending: false,
    isPopular: true,
    league: 'Premier League',
  },
  {
    id: 'a7',
    title: 'Convocation : Belmadi maintient sa confiance aux cadres contre la Guinée',
    summary: 'Le sélectionneur Djamel Belmadi a dévoilé sa liste de 25 joueurs pour le prochain rassemblement de l\'équipe nationale. Les habituels cadres sont présents avec quelques surprises notables.',
    imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&h=450&fit=crop',
    source: SOURCES[6],
    originalUrl: 'https://www.fanatiquez.dz',
    category: 'algerie',
    tags: ['Belmadi', 'Convocation', 'Guinée', 'Fennecs'],
    publishedAt: '2026-03-09T14:00:00Z',
    viewCount: 52000,
    isBreaking: false,
    isTrending: false,
    isPopular: true,
    league: 'CAN',
  },
  {
    id: 'a8',
    title: 'Bundesliga : Leverkusen confirme son titre, Kane au top de sa forme',
    summary: 'Le Bayer Leverkusen s\'est imposé 4-1 face à Dortmund, confirmant sa domination en Bundesliga. Harry Kane a inscrit un doublé, portant son total à 28 buts cette saison.',
    imageUrl: 'https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?w=800&h=450&fit=crop',
    source: SOURCES[5],
    originalUrl: 'https://www.espn.com',
    category: 'matchs',
    tags: ['Leverkusen', 'Bundesliga', 'Kane'],
    publishedAt: '2026-03-09T19:30:00Z',
    viewCount: 28700,
    isBreaking: false,
    isTrending: false,
    isPopular: false,
    league: 'Bundesliga',
  },
];

export const TRANSFERS: Transfer[] = [
  {
    id: 't1',
    player: PLAYERS[0],
    fromClub: CLUBS[0],
    toClub: CLUBS[2],
    status: 'rumeur',
    fee: '20M€',
    source: SOURCES[2],
    article: ARTICLES[0],
    rumourDate: '2026-03-08T10:00:00Z',
    league: 'Premier League',
  },
  {
    id: 't2',
    player: PLAYERS[3],
    fromClub: CLUBS[1],
    toClub: null,
    status: 'officiel',
    fee: 'Prolongation',
    source: SOURCES[3],
    article: ARTICLES[1],
    rumourDate: '2026-02-15T09:00:00Z',
    confirmedDate: '2026-03-10T07:15:00Z',
    league: 'La Liga',
  },
  {
    id: 't3',
    player: PLAYERS[2],
    fromClub: CLUBS[0],
    toClub: CLUBS[5],
    status: 'confirme',
    fee: '25M€',
    contractDuration: '3 ans',
    source: SOURCES[4],
    article: ARTICLES[4],
    rumourDate: '2026-02-20T12:00:00Z',
    confirmedDate: '2026-03-05T16:00:00Z',
    league: 'Premier League',
  },
  {
    id: 't4',
    player: PLAYERS[1],
    fromClub: CLUBS[0],
    toClub: CLUBS[6],
    status: 'rumeur',
    source: SOURCES[0],
    article: ARTICLES[0],
    rumourDate: '2026-03-09T08:00:00Z',
    league: 'La Liga',
  },
  {
    id: 't5',
    player: PLAYERS[4],
    fromClub: CLUBS[0],
    toClub: CLUBS[3],
    status: 'abandonne',
    source: SOURCES[1],
    article: ARTICLES[0],
    rumourDate: '2026-02-10T11:00:00Z',
    league: 'Bundesliga',
  },
];

export const MATCHES: Match[] = [
  {
    id: 'm1',
    homeTeam: CLUBS[0],
    awayTeam: CLUBS[4],
    homeScore: 2,
    awayScore: 1,
    status: 'en_direct',
    kickoffTime: '2026-03-10T20:00:00Z',
    league: 'Champions League',
    stadium: 'Parc des Princes',
    minute: 67,
  },
  {
    id: 'm2',
    homeTeam: CLUBS[7],
    awayTeam: { id: 'c11', name: 'Cameroun', logo: '🦁', league: 'CAN', country: 'Cameroun', color: '#009A44' },
    status: 'a_venir',
    kickoffTime: '2026-03-15T18:00:00Z',
    league: 'CAN',
    stadium: 'Stade Mustapha Tchaker',
  },
  {
    id: 'm3',
    homeTeam: CLUBS[5],
    awayTeam: CLUBS[2],
    homeScore: 3,
    awayScore: 1,
    status: 'termine',
    kickoffTime: '2026-03-09T17:30:00Z',
    league: 'Premier League',
    stadium: 'Emirates Stadium',
  },
  {
    id: 'm4',
    homeTeam: CLUBS[1],
    awayTeam: CLUBS[6],
    homeScore: 2,
    awayScore: 2,
    status: 'termine',
    kickoffTime: '2026-03-09T20:00:00Z',
    league: 'La Liga',
    stadium: 'Santiago Bernabéu',
  },
  {
    id: 'm5',
    homeTeam: CLUBS[3],
    awayTeam: CLUBS[8],
    status: 'a_venir',
    kickoffTime: '2026-03-11T20:30:00Z',
    league: 'Champions League',
    stadium: 'Allianz Arena',
  },
  {
    id: 'm6',
    homeTeam: CLUBS[7],
    awayTeam: { id: 'c12', name: 'Sénégal', logo: '🦁', league: 'CAN', country: 'Sénégal', color: '#009A44' },
    homeScore: 1,
    awayScore: 0,
    status: 'termine',
    kickoffTime: '2026-03-06T18:00:00Z',
    league: 'CAN',
    stadium: 'Stade du 5 Juillet',
  },
];

export const ALGERIAN_PLAYERS_ABROAD: Player[] = [
  {
    id: 'ap1', name: 'Riyad Mahrez', position: 'Ailier droit', nationality: 'Algérie',
    age: 33, currentClub: CLUBS[0], imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=300&h=300&fit=crop',
    isAlgerian: true, jerseyNumber: 26, marketValue: '15M€',
  },
  {
    id: 'ap2', name: 'Youcef Atal', position: 'Latéral droit', nationality: 'Algérie',
    age: 28, currentClub: { id: 'c13', name: 'Nice', logo: '🔴', league: 'Ligue 1', country: 'France', color: '#C8102E' },
    imageUrl: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=300&h=300&fit=crop',
    isAlgerian: true, jerseyNumber: 22, marketValue: '18M€',
  },
  {
    id: 'ap3', name: 'Islam Slimani', position: 'Attaquant', nationality: 'Algérie',
    age: 35, currentClub: { id: 'c14', name: 'Besiktas', logo: '⚫', league: 'Autres', country: 'Turquie', color: '#000000' },
    imageUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=300&h=300&fit=crop',
    isAlgerian: true, jerseyNumber: 9, marketValue: '3M€',
  },
  {
    id: 'ap4', name: 'Sofiane Feghouli', position: 'Milieu offensif', nationality: 'Algérie',
    age: 34, currentClub: { id: 'c15', name: 'Al-Hilal', logo: '🔵', league: 'Autres', country: 'Arabie Saoudite', color: '#003DA5' },
    imageUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=300&h=300&fit=crop',
    isAlgerian: true, jerseyNumber: 10, marketValue: '4M€',
  },
];
